//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude;

pub mod romi_comments;
pub mod romi_fields;
pub mod romi_hitokotos;
pub mod romi_metas;
pub mod romi_news;
pub mod romi_news_comments;
pub mod romi_posts;
pub mod romi_relationships;
pub mod romi_seimgs;
pub mod romi_users;
