//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

// pub use super::romi_comments::Entity as RomiComments;
// pub use super::romi_fields::Entity as RomiFields;
// pub use super::romi_hitokotos::Entity as RomiHitokotos;
// pub use super::romi_metas::Entity as RomiMetas;
// pub use super::romi_news::Entity as RomiNews;
// pub use super::romi_news_comments::Entity as RomiNewsComments;
// pub use super::romi_posts::Entity as RomiPosts;
// pub use super::romi_relationships::Entity as RomiRelationships;
// pub use super::romi_seimgs::Entity as RomiSeimgs;
// pub use super::romi_users::Entity as RomiUsers;
