//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "romi_news")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub nid: u32,
    pub created: Option<u32>,
    pub modified: Option<u32>,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    pub hide: Option<String>,
    pub views: Option<i32>,
    pub likes: Option<i32>,
    pub comments: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub imgs: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
