[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros", "fs"] }

[dependencies.sea-orm-migration]
version = "1.0.0"
features = ["runtime-tokio-native-tls", "sqlx-mysql"]
