//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::romi_articles::Entity as RomiArticles;
pub use super::romi_comments::Entity as RomiComments;
pub use super::romi_metas::Entity as RomiMetas;
pub use super::romi_relationships::Entity as RomiRelationships;
pub use super::romi_users::Entity as RomiUsers;
