[package]
name = "roga"
version = "1.0.0"
edition = "2021"
authors = ["Arimura Sena <me@hotaru.icu>"]
description = "A Fast, beautiful, lightweight, and flexible logging library for Rust"
repository = "https://github.com/biyuehu/datrie"
readme = "README.md"
keywords = ["logger", "log", "record"]
license = "BAN-ZHINESE-LICENSE"

[dependencies]
chrono = "0.4"
colored = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
